version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.10.1
    - 3.4.0
    - 3.6.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: identify
    versions:
    - 1.5.13
    - 1.5.14
    - 1.6.1
    - 2.0.0
    - 2.1.0
    - 2.1.1
    - 2.1.2
    - 2.1.3
    - 2.1.4
    - 2.2.0
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: pyupgrade
    versions:
    - 2.10.0
    - 2.10.1
    - 2.11.0
    - 2.12.0
    - 2.7.4
    - 2.8.0
    - 2.9.0
  - dependency-name: virtualenv
    versions:
    - 20.4.0
    - 20.4.1
    - 20.4.2
    - 20.4.3
  - dependency-name: arrow
    versions:
    - 0.17.0
    - 1.0.2
    - 1.0.3
  - dependency-name: mypy
    versions:
    - "0.800"
  commit-message:
    prefix: ":arrow_up:"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  commit-message:
    prefix: ":arrow_up:"
